# Generated by Django 5.0 on 2023-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
